services:
  mysql-db:
    image: mysql:8.0
    container_name: gestmed-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: scheduling
    ports:
      - "3308:3306"
    volumes:
      - gestmed-mysql-data:/var/lib/mysql

  rabbitmq:
    image: rabbitmq:3-management
    container_name: gestmed-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"

volumes:
  gestmed-mysql-data:
